spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
        prefetch: 1
    template:
      reply-timeout: 84600000
server:
  port: 8686